spring.application.name=demo

server.port=8080

security.mfa.encryption-key=${MFA_ENCRYPTION_KEY}

#jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#h2-solo-test
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#secret
secret.lunghezza-secret=32
secret.caratteri=ABCDEFGHIJKLMNOPQRSTUVWXYZ234567
